%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/kilted/.*$
%global __requires_exclude_from ^/opt/ros/kilted/.*$

Name:           ros-kilted-rsl
Version:        1.1.0
Release:        3%{?dist}%{?release_suffix}
Summary:        ROS rsl package

License:        BSD-3-Clause
Source0:        %{name}-%{version}.tar.gz

Requires:       eigen3-devel
Requires:       fmt-devel
Requires:       ros-kilted-rclcpp
Requires:       ros-kilted-tcb-span
Requires:       ros-kilted-tl-expected
Requires:       ros-kilted-ros-workspace
BuildRequires:  doxygen
BuildRequires:  eigen3-devel
BuildRequires:  fmt-devel
BuildRequires:  ros-kilted-rclcpp
BuildRequires:  ros-kilted-tcb-span
BuildRequires:  ros-kilted-tl-expected
BuildRequires:  ros-kilted-ros-workspace
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%if 0%{?with_tests}
BuildRequires:  clang-tools-extra
BuildRequires:  git
BuildRequires:  range-v3-devel
%endif

%description
ROS Support Library

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
mkdir -p .obj-%{_target_platform} && cd .obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/kilted" \
    -DCMAKE_PREFIX_PATH="/opt/ros/kilted" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
    -DCATKIN_BUILD_BINARY_PACKAGE="1" \
%if !0%{?with_tests}
    -DBUILD_TESTING=OFF \
    -DCATKIN_ENABLE_TESTING=OFF \
%endif
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
%make_install -C .obj-%{_target_platform}

%files
/opt/ros/kilted

%changelog
* Wed Apr 23 2025 Tyler Weaver <maybe@tylerjw.dev> - 1.1.0-3
- Autogenerated by Bloom

* Wed Mar 06 2024 Tyler Weaver <maybe@tylerjw.dev> - 1.1.0-2
- Autogenerated by Bloom

* Wed Dec 20 2023 Tyler Weaver <maybe@tylerjw.dev> - 1.1.0-1
- Autogenerated by Bloom

* Wed Dec 06 2023 Tyler Weaver <maybe@tylerjw.dev> - 1.0.1-1
- Autogenerated by Bloom

* Tue Dec 05 2023 Tyler Weaver <maybe@tylerjw.dev> - 1.0.0-1
- Autogenerated by Bloom

* Thu Mar 23 2023 Tyler Weaver <maybe@tylerjw.dev> - 0.2.2-1
- Autogenerated by Bloom

* Wed Mar 22 2023 Tyler Weaver <maybe@tylerjw.dev> - 0.2.1-2
- Autogenerated by Bloom

* Wed Mar 15 2023 Tyler Weaver <maybe@tylerjw.dev> - 0.2.1-1
- Autogenerated by Bloom

